[package]
name = "buildstatus"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive"] }
csv = "1.3.1"
regex = "1.11.1"
roxmltree = "0.20.0"
